### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by mateusKoppe** [ccuffs/sac#4]
Como vamos utilizar esse código em futuros projetos acredito que seria uma boa ideia dar uma refatorada, penso em implementar uma arquitetura MVC, com URL amigáveis e deixando o código menos procedural do que está hoje.

**Comment by mateusKoppe** [comment]
Já estou trabalhando essa issue no meu fork, assim que tiver algo bom o suficiente eu mando um PR para ser aprovado.

**Comment by Dovyski** [comment]
Excelente! Esse código é muito antigo e foi feito com um cronograma significativamente limitado. Pagamento de dívidas técnicas vai ajudar no crescimento futuro.
