### ISSUE TITLE
Novo README

### ISSUE THREAD

**Issue by mateusKoppe** [ccuffs/sac#60]
A ideia é informar sobre:
- Sobre o projeto;
- Features implementadas e que serão implementadas;
    que serão implementadas:
    - Geração de certificado;
    - Controle de presença;
    - Pagamento online;
- Como rodar;
   os passos são basicamente:
   - As depêndencias são, php, mysql e composer;
   - Instalar as dependências do composer com `composer install`;
   - Criar um banco de dados e gerar a estrutura com o arquivo `database/sac.sql`;
   - Configure o arquivo `App/config.php`;
- Como contribuir;

**Comment by mateusKoppe** [comment]
A ideia é informar sobre:
- O objetivo do projeto;
- Features implementadas e que serão implementadas;
- Como rodar;
- Como contribuir;

**Comment by mellonaomi** [comment]
Poderia fazer uma descrição de como rodar?

**Comment by mateusKoppe** [comment]
Opa! Claro, vou editar na descrição ;)

**Comment by mellonaomi** [comment]
Quais as features que serão implementadas?

**Comment by mateusKoppe** [comment]
Editado :)

**Comment by mateusKoppe** [comment]
Pr #78 feito e mergeado! Tarefa concluída.
