### ISSUE TITLE
Error de segurança em UserController:update

### ISSUE THREAD

**Issue by mateusKoppe** [ccuffs/sac#64]
Não existe uma validação de permissão de usuário para realizar as alterações no método post, isso é uma grave falha de segurança.
Para corrigir é bem simples, é feito essa validações em controllers como por exemplo o EventController, basta reproduzir o mesmo método.

**Comment by EdSabino** [comment]
Posso ajudar com isso :D

**Comment by EdSabino** [comment]
https://github.com/ccuffs/sac/pull/68
ta na mão

**Comment by mateusKoppe** [comment]
Show!!
PR mergeado!
