### ISSUE TITLE
Tabela de preços cria barra de rolagem horizontal

### ISSUE THREAD

**Issue by arturspon** [ccuffs/sac#72]
Na plataforma mobile, dependendo da largura ta tela do dispositivo, a tabela de preços causa uma barra de rolagem horizontal na página.
Talvez utilizar um **scale: none** resolva o problema.
Testado em um smartphone com resolução de 2220x1080.

![Screenshot_20191011-094122_Chrome](https://user-images.githubusercontent.com/22029603/66652238-99c30100-ec0b-11e9-981d-4ee3c9afaa04.jpg)

**Comment by mateusKoppe** [comment]
Obrigado por reportar esse erro!
Você tem disponibilidade para corrigir? Caso contrário adicionarei a label de help wanted.

**Comment by arturspon** [comment]
Feito!
