### ISSUE TITLE
Exibir uma mensagem mais amigavel de inscriçao concluída

### ISSUE THREAD

**Issue by mateusKoppe** [ccuffs/sac#77]
Na tela de perfil no momento está sendo exibido um lista com os pagamentos do usuário, seria mais interessante exibir algo mais chamativo, como um alert-success ou algo nesse sentido. O importante é deixar amigável e informativo os pagamentos e a inscrição do usuário.

**Comment by arufonsekun** [comment]
Hello world, se o _deadline_ dessa _issue_ não for muito apertado, posso ficar com ela.

**Comment by arufonsekun** [comment]
shame on me, depois de 10 dias tô codando essa _issue_ hj

**Comment by arufonsekun** [comment]
Vou fechar essa _issue_

**Comment by arufonsekun** [comment]
Meee não posso fechar 😢

**Comment by mateusKoppe** [comment]
Apaguei teu comentário falando que não deu para apagar, Github mantém histórico de tudo kkk

Fechando a issue!
